apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: monitoramento
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nicolas-limadev/argo-app-for-apps
    targetRevision: HEAD
    path: /app-sets-monitoramento
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true